name: bsr
description: bsr
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Bloc
  ## Presentation (https://pub.dev/packages/bloc / https://pub.dev/packages/flutter_bloc)
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  # Network
  ### Client https://pub.dev/packages/dio
  dio: ^4.0.6
  ### https://pub:dev/packages/connectivity_plus
  connectivity_plus: ^2.3.6

  # Data storage
  ### https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.15
  ### https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^5.1.0

  # DI(Service Locator) https://pub.dev/packages/get_it
  get_it: 7.2.0

  # Utils
  ### https://pub.dev/packages/collection
  collection: ^1.16.0
  ### https://pub.dev/packages/logger
  logger: ^1.1.0

  ### https://pub.dev/packages/json_annotation
  json_annotation: ^4.6.0

  #UI
  ### https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.1.1+1
  ### https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.5

  #Locolization
  ### https://pub.dev/packages/intl
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ### https://pub.dev/packages/build_runner
  build_runner: ^2.2.0
  ### https://pub.dev/packages/json_serializable
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false

Default: false

